import initAnimacaoScroll from './modules/scroll-animacao.js';
import initScrollSuave from './modules/scroll-suave.js';
import initAccordion from './modules/accordion.js';
import initTabNav from './modules/tabnav.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropDownMenu from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initFuncionamento from './modules/funcionamento.js';
import initFethAnimais from './modules/fetch-animais.js';
import initFethBitcoin from './modules/fetch-bitcoin.js';

initAnimacaoScroll();
initScrollSuave();
initAccordion();
initTabNav();
initModal();
initTooltip();
initDropDownMenu();
initMenuMobile();
initFuncionamento();
initFethAnimais();
initFethBitcoin();